SAD TROMBONE RETURNS
HispaniaSS13/ParadiseHispania pull request #11
Opened 2022-11-29 17:08 UTC by bawz0

## What Does This PR Do

regresa el sad trombone al pda del payaso

## Why It's Good For The Game

https://user-images.githubusercontent.com/36208994/204594692-f90d7fcc-91a2-4d09-8835-66baf74f78d1.mp4

## Images of changes

https://user-images.githubusercontent.com/36208994/204594692-f90d7fcc-91a2-4d09-8835-66baf74f78d1.mp

## Testing

https://user-images.githubusercontent.com/36208994/204594692-f90d7fcc-91a2-4d09-8835-66baf74f78d1.mp
## Changelog
:cl:
add: https://user-images.githubusercontent.com/36208994/204594692-f90d7fcc-91a2-4d09-8835-66baf74f78d1.mp4
/:cl:

2022-11-29 17:51 UTC, Helixis requested changes

2022-11-29 17:51 UTC, Helixis commented on code/modules/pda/cart.dm
> -		new /datum/data/pda/utility/honk
Esto no se puede comentar en block y copiar a su propio dm dentro de modular_hispania? Para no tener que tocar este dm original

2022-11-29 18:11 UTC, SagaStars requested changes
Ta casi bien.

2022-11-29 18:11 UTC, SagaStars commented on modular_hispania/code/modules/pda/utilities.dm
> +		last_bone = world.time
```suggestion
/datum/data/pda/utility/trombone/ //wah wah wah
	name = "Sad Trombone"
	icon = "smile-o"
	category = "Clown"

	var/last_bone

/datum/data/pda/utility/trombone/start()
	if(!(last_bone && world.time < last_bone + 40))
		playsound(pda.loc, 'sound/misc/sadtrombone.ogg', 50, 1)
		last_bone = world.time

```

Cuida los espacios.

2022-11-29 18:11 UTC, SagaStars commented on code/modules/pda/cart.dm
> -		new /datum/data/pda/utility/honk
Hmmm no creo que sea necesario para un DM tan poco transitado, seria mas un lio cuando vengan a actualizar algo relacionado con los pda imo. Solo hay que poner los //HISPANIA STARTS y //HISPANIA ENDS

2022-11-29 18:14 UTC, Helixis commented on code/modules/pda/cart.dm
> -		new /datum/data/pda/utility/honk
Ok esa solución está bien

2022-11-29 21:04 UTC, YokoDeChicle commented
Si puedes a futuro anexa el PR donde hicieron el cambio para poder tener una sencilla referencia. 

Estuve buscando y no recuerdo en ningún momento el trombone fuera parte de la PDA del payaso es algo que suena cuando muere uno pero la utilidad en PDA ¿Seguro que estaba antes en la PDA?

2022-11-29 21:06 UTC, kokolo21 approved these changes
Good job. 👍 Nada más que me molesta que el paréntesis no esté en una new line pero no afecta nada. Aprobado.

2022-11-29 21:08 UTC, kokolo21 commented
> Si puedes a futuro anexa el PR donde hicieron el cambio para poder tener una sencilla referencia.
> 
> Estuve buscando y no recuerdo en ningún momento el trombone fuera parte de la PDA del payaso es algo que suena cuando muere uno pero la utilidad en PDA ¿Seguro que estaba antes en la PDA?

Si estaba. Yo mismo hice el PR en el Hispania viejo por unos problemas que tuvo Bawz con el code

2022-11-29 22:46 UTC, Helixis approved these changes

2022-12-17 03:43 UTC, SagaStars approved these changes
Aprobao

2022-12-17 03:55 UTC, merged