Ported cloaker and sus prototype
HispaniaSS13/ParadiseHispania pull request #15
Opened 2022-12-17 15:23 UTC by AsrielFBI

Ported from the old repo the cloaker and sus prototype + fixed/adapted to our new file_system.

## What Does This PR Do

Portea de nuestro vieja repo los PRs:
https://github.com/Helixis/Paradise/pull/1150/files
https://github.com/Helixis/Paradise/pull/997

Además de que los adapta a nuestro nuevo sistema de ficheros
## Why It's Good For The Game

Volvemos a tener un par de objetos interesantes en el juego

## Testing

Probé lo siguiente:
>Pedir en cargo el sus prototype.
>Usar el sus prototype para obtener research.
>Pedir en cargo la caja de cloaker.
>Probar cada línea de sonido de la máscara de cloaker.

## Changelog
:cl:
add: Added cloaker assault crate
add: Added sus machine prototype
add: Added sus machine prototype crate
fix: Fixed the cloaker file_system and paths
soundadd: Added the cloaker mask sounds
imageadd: Added sus machine prototype dmi
/:cl:

2022-12-18 13:44 UTC, kokolo21 requested changes
Fuera del nombre, esta todo bien, que vea.

2022-12-18 13:44 UTC, kokolo21 commented on modular_hispania/code/game/objects/items/devices/syndieprototype.dm
> +	name = "a sus machine prototype"
Ya pasamos lo del amongus, me parece bien que este en la descripción porque suelen ser "funni" las descripciones pero no el nombre jajaja
```suggestion
	name = "suspicious machine prototype"
```

2022-12-18 13:49 UTC, AsrielFBI commented on modular_hispania/code/game/objects/items/devices/syndieprototype.dm
> +	name = "a sus machine prototype"
Pierde la gracia si no es "sus"

2022-12-18 14:31 UTC, Helixis approved these changes

2022-12-18 20:43 UTC, kokolo21 submitted a review, later dismissed

2022-12-20 23:08 UTC, YokoDeChicle submitted a review, later dismissed

2022-12-20 23:08 UTC, YokoDeChicle commented on modular_hispania/code/datums/supplypacks.dm
> +	cost = 120
Ofrece bastante equipamiento para el costo tan bajo que tiene, ya sea reduce un poco los valores que cuesta o directamente lo que consideres a discreción para que tenga un balance de puntos.

Antes estos precios estaban bien pero en Paradise modificaron costos los cuales hacen que ahora este bastante buena esta caja por el costo/beneficio.

Como ejemplo tan solo una caja de SWAT cuesta 800 puntos. Te dejo aquí el archivo donde están los valores en Paradise como referencia.

https://github.com/HispaniaSS13/ParadiseHispania/blob/Lambda/code/modules/supply/supply_packs/pack_security.dm

2022-12-20 23:08 UTC, YokoDeChicle commented on modular_hispania/code/datums/supplypacks.dm
> +	cost = 180
Lo mismo que antes, como dato chistoso mande mi PR Review al antiguo PR por si recibes varias notificaciones.

2022-12-20 23:35 UTC, AsrielFBI commented on modular_hispania/code/modules/clothing/mask/gasmask.dm
> +								"im-late"			= "I know I know, I'm late",
"im_late" es cómo se llama el archivo de audio....

2022-12-20 23:37 UTC, YokoDeChicle commented on modular_hispania/code/modules/clothing/mask/gasmask.dm
> +								"im-late"			= "I know I know, I'm late",
Error mio

2022-12-20 23:39 UTC, AsrielFBI commented on modular_hispania/code/modules/clothing/mask/gasmask.dm
> +								"im-late"			= "I know I know, I'm late",
Pues ya he modificado los precios ya que tenías razón, la economía de para está inflada lol, ¿Algo más que cambiar?

2022-12-20 23:48 UTC, YokoDeChicle reviewed
Hasta que vea que opinan los otros de dar abduction a 4 e ilegal a 4 lo considerare. Como no lo quiero dejar como Aprobado solo lo pondré en Comment.

2022-12-20 23:48 UTC, YokoDeChicle commented on modular_hispania/code/datums/supplypacks.dm
> +	contraband = 1
Aquí hay que agregar el hecho de que sea una caja segura par que tenga consistencia con el resto de cajas de ciencias. 

    containertype = /obj/structure/closet/crate/secure/scisec
	access = ACCESS_RESEARCH
	
Igualmente a futuro por favor evita hacer PR's de temas tan diferentes en uno mismo. Esta vez no tengo problema con aceptarlo pero si llegamos a aceptar una idea o no solo hace mas trabajo para ti y termina retrasando un poco el aprobar tu PR. 

Tengo mis dudas sobre dar Abudction a ciencias por este medio cuando ya tienen otros medios e ilegal a 4 actualmente no se a que tanto de de problemas voy a preguntarlo en el chat de code.

2022-12-20 23:50 UTC, AsrielFBI commented on modular_hispania/code/datums/supplypacks.dm
> +	contraband = 1
Entiendo tú incomodidad con PRs de distintas ideas, no he considerado esta vez que fuera gran problema porque son ports de lo que ya teníamos antes. Con lo que todo ya estaba discutido y lo único que hay que hacer es updatearlo para que siga siendo consistente y ya (ej, los precios), pero todo lo demás son asuntos ya hablados en los PRs mergeados btw.

2022-12-21 15:51 UTC, UmeBelle approved these changes
Port que ya se había aprovado antes, así que por mi bien.

2022-12-21 18:00 UTC, SagaStars requested changes
No comparto totalmente el precio del cloaker gear crate pero; la del prototipo lo pusistes en el precio perfecto. Acomodalo y apruebo.

2022-12-21 21:39 UTC, AsrielFBI commented on modular_hispania/code/datums/supplypacks.dm
> +	cost = 950
Aight, argentina momento. Lo puse al final a 1150

2022-12-22 02:40 UTC, SagaStars approved these changes

2022-12-22 20:35 UTC, Helixis approved these changes

2022-12-22 22:31 UTC, SagaStars approved these changes

2022-12-24 18:04 UTC, kokolo21 approved these changes

2022-12-24 18:04 UTC, merged