Agrega la guia rapida de la space law al juego
HispaniaSS13/ParadiseHispania pull request #16
Opened 2022-12-17 17:49 UTC by Helixis

## What Does This PR Do
Agrega books.dm a modular hispania para que la ley espacial pueda leerse ingame sin afectar otros libros. En lugar de usar un HTML hardcodeado dentro del código, solo tiene un href a http://hispaniastation.net/spacelaw/ . Esto permite alterar la ley espacial en cualquier momento sin tener que volver a tocar el código.

manuals.dm ahora tiene una variable para identificar el libro como hispania_article o no, y se inicializa verificando esa variable con un if.

## Why It's Good For The Game
El libro de la space law de paradise have referencia a la wiki. Esta versión usa un HTML custom con las penas resumidas en tablas de acuerdo a como se sigue la ley espacial en la comunidad

## Images of changes
![image](https://user-images.githubusercontent.com/28197551/208254208-a93d0f07-0186-4f13-addc-e6a3b4a95cb0.png)
Skrell desnudo encuentra un libro de ley espacial.

![image](https://user-images.githubusercontent.com/28197551/208254225-0590ca59-e1d4-40e8-be85-1d44b978720d.png)
El libro abre como siempre, al presionar next page sale la lista de htmls

![image](https://user-images.githubusercontent.com/28197551/208254613-1aec73d7-660b-4560-a175-7c6c45f4f4c5.png)
El libro contiene todos los crímenes y la ventana es resizable. El skrell quizás siga desnudo pero al menos ahora está jurídicamente informado.

## Testing
Probado ingame, carga el código siempre

## Changelog
:cl:
tweak: El libro de la space law ahora está disponible ingame correctamente
/:cl:

2022-12-17 19:45 UTC, AsrielFBI submitted a review, later dismissed
cool

2022-12-18 13:45 UTC, kokolo21 requested changes
Fuera de esos cambios que sugerí, solido el código 👍

2022-12-18 13:45 UTC, kokolo21 commented on modular_hispania/code/game/objects/items/weapons/manuals.dm
> +	hispania_article_title = "spacelaw"
En lugar de comentar el original, diria hacerlo de esta manera para tocar lo menos posible de paradise. y quitar los cambios que hiciste a manuals.dm de paradise

```suggestion
/obj/item/book/manual/wiki
	var/hispania_article_title = "spacelaw" //valor default
	var/hispania_article = TRUE

/obj/item/book/manual/wiki/Initialize()
	. = ..()
	if(hispania_article) //revisa si el libro tiene la variable hispania article true, si no lo inicializa para paradise
		pages = list({"
		<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /></head><body bgcolor='[book_bgcolor]'>
		<a href="http://hispaniastation.net/[hispania_article_title]">Continuar</a>
		</body></html>"})
	else
		pages = list({"
		<html><head></head><body bgcolor='[book_bgcolor]'>
		<iframe width='100%' height='97%' src="[GLOB.configuration.url.wiki_url]/index.php/[wiki_article_title]?action=render" frameborder="0" id="main_frame"></iframe>
		</body></html>"})

/obj/item/book/manual/wiki/security_space_law
	hispania_article = TRUE
	hispania_article_title = "spacelaw"
```

2022-12-18 14:28 UTC, Helixis commented on modular_hispania/code/game/objects/items/weapons/manuals.dm
> +	hispania_article_title = "spacelaw"
Listo, cambios hechos

2022-12-18 14:33 UTC, kokolo21 approved these changes
Esta bien asi 👍 
Probaste que andara con estos cambios?

2022-12-18 14:38 UTC, Helixis commented
> Esta bien asi 👍 Probaste que andara con estos cambios?

Sí

2022-12-18 18:13 UTC, UmeBelle approved these changes
Muy bonito

2022-12-18 19:37 UTC, AsrielFBI approved these changes

2022-12-18 19:37 UTC, merged