Clothelate3electric
HispaniaSS13/ParadiseHispania pull request #18
Opened 2022-12-18 14:39 UTC by kokolo21

## What Does This PR Do

Agrega la Clothelate que estaba antes en hispania
## Why It's Good For The Game

Forma de agregar ropas custom al juego, solo hace falta agregar la ropa a clothelate_designs y aparecera.
Y tambien para tener un capitan vestido de bigchungus.
## Images of changes

![image](https://user-images.githubusercontent.com/94068050/208304446-0dc92e16-44be-4617-831c-1c2674c0a626.png)

## Testing

Agrege la clothelate, la probe, tira la ropa, se puede hackear y tal. 
Faltan ropas pero eso ya se puede agregar a futuro.

2022-12-18 16:38 UTC, Helixis submitted a review, later dismissed

2022-12-20 22:12 UTC, AsrielFBI approved these changes
ofc yes

2022-12-21 00:51 UTC, YokoDeChicle reviewed
Me agrada la idea de tener una dispensadora única de nuestras ropas pero prefiero mas la idea de tener una vending propia como lo era el Xtra o anexar nuestras prendas a las vendings existentes. 

Tener que crear una maquina que cree las prendas desde 0 no lo veo como una buena solución a esto.

Entiendo la funcionalidad y le veo futuro a la idea tal vez con alguien de servicio encargado de crear prendas puede, pero de otra forma no considero sea necesaria. 

En cualquier caso si la mayoría lo aprueba reviso el código antes del mergeo.

2022-12-21 00:53 UTC, AsrielFBI commented
> Me agrada la idea de tener una dispensadora única de nuestras ropas pero prefiero mas la idea de tener una vending propia como lo era el Xtra o anexar nuestras prendas a las vendings existentes.
> 
> Tener que crear una maquina que cree las prendas desde 0 no lo veo como una buena solución a esto.
> 
> Entiendo la funcionalidad y le veo futuro a la idea tal vez con alguien de servicio encargado de crear prendas puede, pero de otra forma no considero sea necesaria.
> 
> En cualquier caso si la mayoría lo aprueba reviso el código antes del mergeo.

Es un port btw.
https://github.com/Helixis/Paradise/pull/1157
La idea es que con la máquina puedes obtener también ropas especiales que no se pueden obtener o que son ocultas. Lo que le da cierta utilidad y motivos a ciencias para producirla tho

2022-12-21 15:53 UTC, UmeBelle approved these changes
Aprobado, pero si veo un capitan vestido de big chungus te voy a [contrario a reparar] las piernas.

2022-12-21 16:19 UTC, YokoDeChicle requested changes
Aparte de eso yo pediría que al imprimir ropa lo hiciera con biomateria como lo hace la maquina del botánico pero tengo entendido ya no puedo criticar tu idea o concepto solo mirar que funcione al ser un port, así que esos cambios de nombre y también me resulta extraño que con ilegal puedas imprimir ropa con valores altos de armadura pero bueno, buen código hasta ahora. 

Ahora hay que recordar recompilar TGUI con cada update.

2022-12-21 16:19 UTC, YokoDeChicle commented on modular_hispania/code/modules/research/designs/machine_designs.dm
> +	req_tech = list("engineering" = 3, "illegal" = 2)
"syndicate" = 2

No existe Illegal como una tech para poder imprimir. Igualmente no entiendo por que una impresora de ropa tiene tecnología del sindicato.

2022-12-21 16:19 UTC, YokoDeChicle commented on modular_hispania/code/modules/research/designs/clothelate_designs.dm
> +/*/datum/design/chemist_suit
¿Por que toda esta parte del código esta comentado?

2022-12-21 16:19 UTC, YokoDeChicle commented on modular_hispania/code/game/machinery/clothelate.dm
> +		to_chat(user, "<span class='alert'>The autolathe is busy. Please wait for completion of previous operation.</span>")
Este es el clothlate no el autolathe.

2022-12-21 16:19 UTC, YokoDeChicle commented on modular_hispania/code/game/machinery/clothelate.dm
> +					to_chat(user, "<span class='warning'>This design has already been loaded into the autolathe.</span>")
Igualmente clothlathe no autolathe.

2022-12-21 16:19 UTC, YokoDeChicle commented on modular_hispania/code/game/machinery/clothelate.dm
> +			to_chat(user, "<span class='warning'>This is not the correct type of disk for the autolathe!</span>")
Detalle de nombre de autolathe por clothlathe.

2022-12-22 20:42 UTC, AsrielFBI commented on modular_hispania/code/modules/research/designs/machine_designs.dm
> +	req_tech = list("engineering" = 3, "illegal" = 2)
1: Está bien que hayas visto el problema, es verdad que es "syndicate" en vez de "illegal"
2: Tús opiniones personales son subjetivas y no acarrean ningún valor en un PR de Porteo.
3: Esta tech literalmente es "The study of technologies that violate standard Nanotrasen regulations." No sé dónde pone que sea 100% tecnología del sindicato.

2022-12-22 22:36 UTC, Helixis submitted a review, later dismissed

2022-12-24 19:46 UTC, kokolo21 commented on modular_hispania/code/modules/research/designs/machine_designs.dm
> +	req_tech = list("engineering" = 3, "illegal" = 2)
Arreglado

2022-12-24 19:47 UTC, kokolo21 commented on modular_hispania/code/game/machinery/clothelate.dm
> +		to_chat(user, "<span class='alert'>The autolathe is busy. Please wait for completion of previous operation.</span>")
Arreglado!

2022-12-24 19:47 UTC, kokolo21 commented on modular_hispania/code/game/machinery/clothelate.dm
> +					to_chat(user, "<span class='warning'>This design has already been loaded into the autolathe.</span>")
Arreglado!

2022-12-24 19:47 UTC, kokolo21 commented on modular_hispania/code/game/machinery/clothelate.dm
> +			to_chat(user, "<span class='warning'>This is not the correct type of disk for the autolathe!</span>")
Arreglado!

2022-12-24 19:58 UTC, AsrielFBI approved these changes
Lo veo ya perfectamente ready

2022-12-24 20:19 UTC, Helixis approved these changes

2022-12-26 23:50 UTC, YokoDeChicle approved these changes

2022-12-29 11:34 UTC, merged