KA experimentales
HispaniaSS13/ParadiseHispania pull request #19
Opened 2022-12-18 22:23 UTC by kokolo21

## What Does This PR Do

Agrega de nuevo los KA que teniamos antes  !
## Why It's Good For The Game

Porque ayudan a los pobres mineros discapacitados que tenemos aqui. ademas que estan balanceados.
## Images of changes

![image](https://user-images.githubusercontent.com/94068050/208318960-65777bcd-3603-472d-aec5-e353e369ba8a.png)
![image](https://user-images.githubusercontent.com/94068050/208319012-621f4890-ee45-435f-b539-13635e0a7b28.png)

## Testing

2022-12-18 23:12 UTC, AsrielFBI approved these changes
yas

2022-12-19 00:52 UTC, Helixis approved these changes

2022-12-20 22:12 UTC, AsrielFBI approved these changes
What, no se había aplicado mi aprobado XD

2022-12-21 00:44 UTC, YokoDeChicle requested changes
Lo probe y no da problemas, pero esa doble declaración de variable no termino de comprender que hace, en cualquier caso buen trabajo solo ese detalle y ya doy el aprobado.

2022-12-21 00:44 UTC, YokoDeChicle commented on modular_hispania/code/modules/mining/machine_vending.dm
> +#define EQUIPMENT(n, o, p) n = new /datum/data/mining_equipment(n, o, p)
Esta definida dos veces EQUIPMENT para poder lograr ¿Que cosa? Puede que sea una forma de resolver un conflicto que encontraste pero no me imagino cual debió ser.

2022-12-24 02:13 UTC, kokolo21 commented on modular_hispania/code/modules/mining/machine_vending.dm
> +#define EQUIPMENT(n, o, p) n = new /datum/data/mining_equipment(n, o, p)
Habia sido un error.
Ahora esta fixeado, queria undefine pero debo haberme dormido y lo copie y pegue.

2022-12-24 20:20 UTC, Helixis approved these changes

2022-12-24 20:21 UTC, Helixis commented
Al parecer faltó commitear paradise.dme y por eso da un error de conflictos, no va a dejar mergear si no se arregla.

2022-12-24 20:31 UTC, AsrielFBI submitted a review, later dismissed

2022-12-29 15:20 UTC, YokoDeChicle submitted a review, later dismissed
Deberíamos acreditar estos ports a los respectivos autores que los crearon a futuro simplemente con dejarlo en el titulo para seguir reconociendo lo que ellos hicieron sean o no parte activa de la comunidad.

2023-01-03 00:34 UTC, Helixis approved these changes

2023-01-07 12:21 UTC, AsrielFBI approved these changes

2023-01-07 16:17 UTC, YokoDeChicle approved these changes

2023-01-07 18:31 UTC, merged