Feed me, evento de comida ha vuelto con mejoras
HispaniaSS13/ParadiseHispania pull request #26
Opened 2022-12-31 22:58 UTC by Tilk1

El evento feed me. Ha vuelto mejorado. Los dialogos funcionan mejor que antes

https://github.com/Helixis/Paradise/pull/1153

Se agregaron algunos platillos

Todo fue testeado y adaptado a los cambios del code de paradise del manejo de los puntos de spawns

2023-01-03 00:36 UTC, Helixis approved these changes
Aprobado porque ya había sido previamente aprobado

2023-01-03 02:41 UTC, kokolo21 commented
Recuerda que todo cambio a los archivos de paradise tienen que ir con //HISPANIA CHANGES START y terminar con //HISPANIA CHANGES END 
Para saber exactamente que cambios hicimos al source y para arreglarlo facilmente si es sobreescrito en alguna actualización de Paradise.

2023-01-03 16:40 UTC, AsrielFBI approved these changes
Tiene lo del HISPANIA STARTS ya puesto, no tengo ninguna objeción más.

2023-01-03 17:17 UTC, Helixis approved these changes

2023-01-04 22:52 UTC, UmeBelle requested changes
code/modules/events/feedme.dm

Muevelo al directorio de hispa y estamos bien.

2023-01-12 22:54 UTC, Helixis approved these changes
Aprobado pero tiene conflictos de merge

2023-01-13 12:42 UTC, UmeBelle approved these changes
Movido y request cumplida, aprobao

2023-01-13 12:52 UTC, Helixis approved these changes

2023-01-13 12:52 UTC, merged