Tweak Roles permitidos para Antagonistas
HispaniaSS13/ParadiseHispania pull request #3
Opened 2022-11-09 22:41 UTC by YokoDeChicle

## What Does This PR Do

CMO, RD, CE, HoP no pueden iniciar como antagonistas de Changeling, Cult, Traitor y Vampiro.

Cargos de Seguridad no puede iniciar como Blob.

## Why It's Good For The Game
Balance de los antagonistas para la población actual del servidor. 

## Changelog
:cl:
tweak: Roles permitidos para Antagonistas
/:cl:

2022-11-11 05:18 UTC, UmeBelle requested changes
Puedes centralizar estos cambios en un archivo exclusivo de hispania para no tocar los de Paradise? Te tomara un poco mas pero a la larga va a ser un dolor de cabeza menos.

2022-11-11 05:56 UTC, Evankhell561 commented
> Puedes centralizar estos cambios en un archivo exclusivo de hispania para no tocar los de Paradise? Te tomara un poco mas pero a la larga va a ser un dolor de cabeza menos.

creo que en este caso es dificil de hacer. Y aun si se pudiera creo que es de las cosas que es mejor dejar en el archivo original

2022-11-22 19:22 UTC, SagaStars approved these changes
Muchas gracias.

2022-11-29 17:59 UTC, Helixis approved these changes

2022-11-29 21:10 UTC, kokolo21 approved these changes

2022-11-29 21:32 UTC, UmeBelle approved these changes
Esta vez va a ser aprobado porque es necesario para el balance, pero lo mejor es tomar un poco mas de tiempo y buscar una alternativa.

2022-11-29 21:32 UTC, merged