is_back
HispaniaSS13/ParadiseHispania pull request #33
Opened 2023-01-08 01:21 UTC by Tilk1

![image](https://user-images.githubusercontent.com/24284918/211176477-e9f1a462-408c-475e-adda-945d381fba3f.png)

https://github.com/Helixis/Paradise/pull/334

vuelve Xtra la vending machine.!!

Proximamente estare implementando una vending machine con precios mas altos y otros productos de estilo similar

2023-01-11 00:31 UTC, Helixis commented
Tiene conflictos de merge

2023-01-12 17:17 UTC, SagaStars requested changes
Nada mal pero vamos a necesitar los cambios en todos los mapas para rotacion, cyberiad no es el unico mapa jugable.

2023-01-12 18:37 UTC, Tilk1 commented
> Nada mal pero vamos a necesitar los cambios en todos los mapas para rotacion, cyberiad no es el unico mapa jugable.

No tengo problema en agregarlo pero vale la pena hacer cambios a esos 2 mapas q de todos modos no les vamos a dar mas mantenimiento?

2023-01-13 08:23 UTC, AsrielFBI commented
Opino igual que el resto de mapas no deberíamos tocarlos mucho porque no entran en rotación y así nos evitamos futuros conflictos de mapas. Esto no importaría si tuvieramos ya nuestra propia carpeta con los mapas para modificarlos libremente.

2023-01-13 13:05 UTC, UmeBelle commented
Yo apruebo. A ver que dice Saga con lo de los mapas.

2023-01-13 13:06 UTC, UmeBelle approved these changes
lo que dije en el comentario otra vez me equivoque TENGO PUTO RETRASO

2023-01-14 06:04 UTC, SagaStars approved these changes
No esta en el mismo puesto que estaria la premium vending? Huele a conflictooos para uno de los dos PRs jijiji

2023-01-14 06:05 UTC, merged