Tweak Multiplicador de Eventos
HispaniaSS13/ParadiseHispania pull request #4
Opened 2022-11-09 22:48 UTC by YokoDeChicle

## What Does This PR Do
Modifica el multiplicador de eventos para numero total de jugadores en metas que actualmente alcanzamos de forma constante.

## Why It's Good For The Game
Proporciona metas realistas para el multiplicador y de esta forma pueda alcanzar un ciclo constante de eventos aleatorios en base a números constantes que se alcanzan en el servidor, anteriormente se encontraba fijado para una top player base de 80 jugadores con esto bajamos ese limite a alcanzar para 30 jugadores de esta forma mas eventos aleatorios suceden de forma constante en base a el top de jugadores que hay en el server, esperamos asi se pueda divertir mas la gente disfrutando de los múltiples eventos que se ofrecen.

El tiempo entre eventos se calcula en una multiplicación de un numero aleatorio generado entre los limites de EVENT_DELAY_LOWER y EVENT_DELAY_UPPER (estos dos valores se definen dentro del archivo base de config) por playercount_modifier (numero que escala en base a pop del server). Donde en cada caso de EVENT_DELAY_LOWER y EVENT_DELAY_UPPER se modifica en base a la severidad de los 3 valores existentes Mundane, Moderate y Severe Esto se representa como:

event_delay = rand(config.event_delay_lower[severity], config.event_delay_upper[severity]) * playercount_modifier

## Changelog
:cl:
tweak: Multiplicador de eventos
/:cl:

2022-11-11 05:28 UTC, UmeBelle reviewed
So, si entendí bien, lo que estás queriendo hacer es que los eventos sean mas constantes a una proporción de player mas baja?
Ej: Antes debían haber 80 players para 10 eventos. Y ahora se necesitan 30 para esos 10 eventos.

Ciertamente no estoy familiarizada con el codigo de eventos.

Por cierto, busca un camino para no tocar codigo de Paradise.

2022-11-15 15:05 UTC, YokoDeChicle commented
Este es de los que no creo poder llegar a modificar para evitar tocar el codigo de Paradise, son valores directos a una condicional no una variable o algo similar que pueda volver a declarar posteriormente.

2022-11-22 19:23 UTC, SagaStars approved these changes
Ta bien.

2022-11-29 20:18 UTC, UmeBelle commented
Lo siento pero no me parece un cambio lo suficientemente necesario/importante para tocar el code de Paradise. Haz un archivo duplicado o algo, que genere menos cambios al actualizar desde Paradise.

2022-11-29 20:18 UTC, UmeBelle requested changes
Lo que dije en el otro comentario, le di al boton equivocado.

2023-01-03 00:41 UTC, closed without merging