Nueva vending productos PREMIUM
HispaniaSS13/ParadiseHispania pull request #45
Opened 2023-01-12 21:02 UTC by Tilk1

Agrega una nueva vending machine con precios MUY caros, dando mas incentivo a la gente de juntar dinero para items esteticos aunque bastante interesantes y cuanto mas caro mas especiales!!!

Sin duda un gran desafio para los tripulantes que les gusta estar a la moda y los retos para juntar dinero.

- Agrega tambien la flash custom de among us
- Cuenta con casi todos los items que funcionan customs de paradise. Entre ellos la popular cat backpack y vox caster que antes estaban en el loadout

Algunos productos:
![image](https://user-images.githubusercontent.com/24284918/212180280-407c1d00-d98f-4e46-9cb5-0e36b1d1e576.png)
![image](https://user-images.githubusercontent.com/24284918/212180357-f6bfd040-3cff-4a1b-b56a-31380f530f17.png)

2023-01-12 22:50 UTC, Helixis submitted a review, later dismissed

2023-01-12 23:41 UTC, SagaStars requested changes
Me gusta la idea pero estos precios son ridiculos, el maximo deberia de ser 2500 si no quieres que los unicos que puedan llegar a tener estos objetos sean heads. Tambien trata de poner mas consistente los precios respecto a objeto, los 3 objetos del final van genial pero luego va una chaqueta que nada mas es purpura? Un cosmetico que sea un recolor no deberia pasar de los 250 VS los que son un resprite podrian ir entre los 300-500, mientras tanto los objetos de conversion deberian de liderar la lista.

Me pasas screenshot de los resultados.

2023-01-13 00:52 UTC, Tilk1 commented
> Me gusta la idea pero estos precios son ridiculos, el maximo deberia de ser 2500 si no quieres que los unicos que puedan llegar a tener estos objetos sean heads. Tambien trata de poner mas consistente los precios respecto a objeto, los 3 objetos del final van genial pero luego va una chaqueta que nada mas es purpura? Un cosmetico que sea un recolor no deberia pasar de los 250 VS los que son un resprite podrian ir entre los 300-500, mientras tanto los objetos de conversion deberian de liderar la lista.
> 
> Me pasas screenshot de los resultados.

Es una vending premium, la idea esq los ultimos items sean practicamente inalcanzables. Similar a la bike de los arcade que todos juntan muchos tickets para poder comprar.  Aqui sucede lo mismo, la idea es no poder comprar estos items al spawnear. Solamente los que descubran la forma de juntar muchisimos creditos con suerte podran comprar algun item caro en esa ronda.  Luego en otra ronda repetiran el proceso hasta ir descubriendolos todos.

La chaqueta purpura le puse un costo elevado porque es militar y porque tiene 20 sprites de distintos colores. Es bastante particular,  no habia visto nunca un objeto con tanta versatilidad.

2023-01-14 06:02 UTC, SagaStars approved these changes
No estoy realmente en contra de tu vision asi que paso concedido, veremos como opina la playerbase

2023-01-14 06:03 UTC, SagaStars commented
Resuelve conflictos.

2023-01-14 16:42 UTC, Helixis approved these changes

2023-01-14 23:25 UTC, AsrielFBI requested changes
No?

2023-01-14 23:25 UTC, AsrielFBI commented on config/example/config.toml
> +override_map = "/datum/map/test_tiny"
????

2023-01-14 23:40 UTC, Tilk1 commented on config/example/config.toml
> +override_map = "/datum/map/test_tiny"
sorry me eqivoque y cambie el config del example en vez del otro. Ya lo arreglo

2023-01-14 23:54 UTC, AsrielFBI approved these changes

2023-01-15 01:04 UTC, Helixis approved these changes

2023-01-15 01:04 UTC, merged