Add Hispania Icon Window and Name
HispaniaSS13/ParadiseHispania pull request #5
Opened 2022-11-09 23:25 UTC by YokoDeChicle

## What Does This PR Do
Agrega el nombre correcto al cliente del juego y nuestro icono al mismo. Esta carpeta funciona de forma diferente y no puedo comentar ese código o anidar la imagen en otra carpeta por la estructura de DM. 

## Images of changes
![imagen](https://user-images.githubusercontent.com/117837955/200963389-b11ff6e5-639f-4cf1-9e12-0c84ffeb685d.png)
![imagen](https://user-images.githubusercontent.com/117837955/200963416-24fd954a-e51b-4617-9a34-81c6f7ade8a6.png)

## Changelog
:cl:
tweak: Hispania Icon Windows
/:cl:

2022-11-11 00:03 UTC, Evankhell561 requested changes

2022-11-11 00:03 UTC, Evankhell561 commented on interface/skin.dmf
> -	elem
evita hacer este cambio innecesario porque luego resolver conflictos es molesto

2022-11-11 05:34 UTC, UmeBelle requested changes
Mete el icon de hispania en una carpeta llamada `hispania` dentro de la carpeta `icon`, ahí deben situarse todos los sprites. Revierte los cambios en las lineas 7, 11, 19, 22, 28, 80, 107, 109, 120 y 122. No se si haya una forma de cambiar esto para que no sea tedioso traer cambios de Paradise.

2022-11-13 03:52 UTC, UmeBelle approved these changes
Todo correcto.

2022-11-13 03:53 UTC, merged