Agregadas animaciones
HispaniaSS13/ParadiseHispania pull request #58
Opened 2023-01-17 02:06 UTC by Tilk1

Medbay es mas feliz ahora que ven su trabajo

Agregadas animaciones al inyectar con syringes y hyposprays

Baystation lo tiene, es logico que exista. Nadie presta atencion al chat y cuando estas curando a alguien parece q te quedas viendole como tonto cuando estas ayudandole

![image](https://user-images.githubusercontent.com/24284918/212793958-c25b18d9-cb66-42b0-aece-4804db7bf27e.png)

2023-01-19 12:25 UTC, UmeBelle requested changes
Poe favor pon un gif o video enseñando las animaciones. Tambien especifica mejor el nombre y desc de tu pr, son animaciones en general? De borg? De carbon? Ambas?

2023-01-20 04:28 UTC, Tilk1 commented
> Poe favor pon un gif o video enseñando las animaciones. Tambien especifica mejor el nombre y desc de tu pr, son animaciones en general? De borg? De carbon? Ambas?

https://user-images.githubusercontent.com/24284918/213617287-feda9f3b-cd24-4d9c-b652-065c6993fc7e.mp4

Son de borg y de carbon , con las syringe y hyposprays.  Despues de jugar baystation me di cuenta q queda bastante weird no tener una animacion al curar a las personas

2023-01-22 01:03 UTC, kokolo21 submitted a review, later dismissed
Se ve bien, el codigo es funcional y simple. 👍

2023-01-24 23:35 UTC, Tilk1 commented
Todo en modular_hispania pero agregado el sonido para el hypospray

2023-01-24 23:40 UTC, closed without merging