Agregados alt jobs asistente, aprendiz
HispaniaSS13/ParadiseHispania pull request #62
Opened 2023-01-18 20:15 UTC by Tilk1

Porque todos los jobs estan en ingles menos el de aprendiz? 

![no-hay-por-que-china-enojada](https://user-images.githubusercontent.com/24284918/213285105-1e56429e-f824-49f5-aaee-7d7ec8695979.gif)

Hablando enserio el aprendiz es tan aprendiz que no domina bien el idioma ingles, por eso necesita que su titulo este en español

2023-01-18 21:48 UTC, SagaStars submitted a review, later dismissed

2023-01-19 12:58 UTC, UmeBelle requested changes
Nica, tenemos una peticion, podrías hacer el aprendiz un job aparte?

Un nuevo llega, y lee que solo tiene aprendiz, va a ser mas fácil
El job de asistonto se desbloquearía con 3h de aprendiz
Así un nuevo nuevito es fácil de reconocer y ayudar
Tambien bloquearía el aprendiz luego de 9h de jugarlo y/o si la cuenta de esa persona fue creada hace mas de 14 días, para que jugadores viejos no entren a querer hacerse los trolls
Tengan en cuenta que cada ronda dura un promedio de 2h
Asi que estamos hablando de 5 rondas maso, osea que en una semana o dos se bloquea el job
Depende cuanto vicie

2023-01-19 12:59 UTC, UmeBelle commented
> Nica, tenemos una peticion, podrías hacer el aprendiz un job aparte?
> 
> Un nuevo llega, y lee que solo tiene aprendiz, va a ser mas fácil El job de asistonto se desbloquearía con 3h de aprendiz Así un nuevo nuevito es fácil de reconocer y ayudar Tambien bloquearía el aprendiz luego de 9h de jugarlo y/o si la cuenta de esa persona fue creada hace mas de 14 días, para que jugadores viejos no entren a querer hacerse los trolls Tengan en cuenta que cada ronda dura un promedio de 2h Asi que estamos hablando de 5 rondas maso, osea que en una semana o dos se bloquea el job Depende cuanto vicie

Si me he copypasteado lo que puse en discord

2023-01-20 07:41 UTC, Tilk1 commented
Tome en cuenta las peticiones y lo he testado. Hay una nueva variable que restringe experiencia a la inversa. 

Hay que aclarar que igual el nuevo tiene acceso a los demas jobs que nunca estuvieron bloqueados por experiencia, como cargo  y los de servicio.
![image](https://user-images.githubusercontent.com/24284918/213642495-39b9514e-07dd-4235-827c-aa9e765fa985.png)

Notaran que maneja el mismo FLAG que asistente.  Esto es porque no encontre ninguna forma de ponerlo arriba junto con el asistente. Y hacerlo un job con su propio flag traia muchos problemas.  Intente poner en modular_hispania todo loq pude y no deberia hacer falta hacer cambios ala DB

2023-01-21 13:41 UTC, Helixis submitted a review, later dismissed

2023-02-09 03:56 UTC, Helixis approved these changes

2023-02-10 13:38 UTC, UmeBelle approved these changes
Perdona la demora, me gusta, incluso el equipamiento está muy bonito. Muy buen trabajo.

2023-02-10 13:39 UTC, merged