The Engiberia Update
HispaniaSS13/ParadiseHispania pull request #68
Opened 2023-01-19 18:42 UTC by AsrielFBI

## What Does This PR Do
Portea de vuelta TODOS los PRs relacionados al mapa de Engiberia + fixea los problemas de compatibilidad con el mapa y code actuales.

## Images of changes

![imagen](https://user-images.githubusercontent.com/56162938/213531362-a92e2886-2377-4059-ab04-999b29ad637d.png)
![imagen](https://user-images.githubusercontent.com/56162938/213531406-d6455a66-9a60-4d22-80c5-c4ba414470d3.png)
![imagen](https://user-images.githubusercontent.com/56162938/213531443-f58d7cdd-7534-4eb5-b3fe-d683a5959f24.png)
![imagen](https://user-images.githubusercontent.com/56162938/213531485-0a61d352-a511-4a0b-b279-d0f8faec6227.png)
![imagen](https://user-images.githubusercontent.com/56162938/213531518-2776be27-32db-47df-b479-10cd6c86f3e6.png)
![imagen](https://user-images.githubusercontent.com/56162938/213531713-3b78bb1f-141e-476c-a2c9-5427c4c64d50.png)

## Testing

>Testeada SM
>Testeado Singulo
>Testeado cableamiento
>Testeado dipossals
>Testeado atmos
>Testeado infraestructura general (comprobar brechas)

2023-01-21 20:17 UTC, SagaStars approved these changes
Ya hecho multiples commits al PR reparando ciertos detalles, lo veo bien para aprobar.

2023-01-21 20:18 UTC, SagaStars approved these changes
Ya hecho multiples commits (Uno mas esta vez) al PR reparando ciertos detalles, lo veo bien para aprobar.

2023-01-23 19:04 UTC, kokolo21 commented
Ok iba a aceptarlo pero primero unas cosas.
Si bien no estoy exactamente feliz que ingenieria aumente tanto de tamaño solo porque si, especialmente cuando somos un server de 20 pop, no me opongo. 
A lo que si me opongo es la cantidad de cosas que hay extra solo porque si, que no son necesarias para nada, especialmente para la pop que tenemos. Haz los cambios que pongo aqui y se mergea

1) Esta parte esta completamente innecesaria, no hace falta que ingenieria tenga 2 evas civiles mas alli porque si. 
![image](https://user-images.githubusercontent.com/94068050/214122485-be141ebc-736e-4a60-b462-35c72f60bed6.png)
---------
2) Agrega mas ventanas de maint al abandoned assembly line, ahora que no se puede ver desde el pasillo central, estaria mejor que se pudiera ver en varios lugares mas, no hace falta que sea tan secreta.
![image](https://user-images.githubusercontent.com/94068050/214123136-d57f9807-8127-4a64-84f9-594be4024e8a.png)
---------
3) Porque, justo al lado de ingenieria, hay la única consola de cámaras de sec funcionales fuera de sec y bridge, además del único spawn de handcuffs garantizado? No es necesaria esa sección, quitala o saca las camaras y las handcuffs.
![image](https://user-images.githubusercontent.com/94068050/214123405-7947a72b-92e4-4929-84e1-575ee1d0dc64.png)
---------
4) Lo mismo que con el punto 1, Ya tienen 4 Atmos suits y 4 engi suits, no hacen falta 2 mas en el secure storage, creo que ni hay tantos slots de inge. 
![image](https://user-images.githubusercontent.com/94068050/214125081-af778b7f-bdcd-476b-83e1-94be7202e1c7.png)
---------

2023-01-23 20:18 UTC, AsrielFBI commented
> Ok iba a aceptarlo pero primero unas cosas.
> Si bien no estoy exactamente feliz que ingenieria aumente tanto de tamaño solo porque si, especialmente cuando somos un server de 20 pop, no me opongo. 
> A lo que si me opongo es la cantidad de cosas que hay extra solo porque si, que no son necesarias para nada, especialmente para la pop que tenemos. Haz los cambios que pongo aqui y se mergea
> 
> 1) Esta parte esta completamente innecesaria, no hace falta que ingenieria tenga 2 evas civiles mas alli porque si. 
> ![image](https://user-images.githubusercontent.com/94068050/214122485-be141ebc-736e-4a60-b462-35c72f60bed6.png)
> ---------
> 2) Agrega mas ventanas de maint al abandoned assembly line, ahora que no se puede ver desde el pasillo central, estaria mejor que se pudiera ver en varios lugares mas, no hace falta que sea tan secreta.
> ![image](https://user-images.githubusercontent.com/94068050/214123136-d57f9807-8127-4a64-84f9-594be4024e8a.png)
> ---------
> 3) Porque, justo al lado de ingenieria, hay la única consola de cámaras de sec funcionales fuera de sec y bridge, además del único spawn de handcuffs garantizado? No es necesaria esa sección, quitala o saca las camaras y las handcuffs.
> ![image](https://user-images.githubusercontent.com/94068050/214123405-7947a72b-92e4-4929-84e1-575ee1d0dc64.png)
> ---------
> 4) Lo mismo que con el punto 1, Ya tienen 4 Atmos suits y 4 engi suits, no hacen falta 2 mas en el secure storage, creo que ni hay tantos slots de inge. 
> ![image](https://user-images.githubusercontent.com/94068050/214125081-af778b7f-bdcd-476b-83e1-94be7202e1c7.png)
> ---------

Es un Port, lol. Ya se discutieron todo el tema de cosas que se añadían ¿Es necesario repetir todas esas parrafadas de texto? Lo veo molesto tbh

2023-01-23 20:50 UTC, kokolo21 requested changes
Lo que puse arriba. ^ Son cosas de balance de juego.

2023-02-02 16:42 UTC, kokolo21 approved these changes
👍 cosas arregladas, veremos si se cambia a futuro pero eso ya es problema para asriel y vonny del futuro.

2023-02-02 18:24 UTC, Helixis approved these changes

2023-02-02 18:24 UTC, merged

2023-07-27 23:00 UTC, miguelop1 commented
viva españa