Vuelve Nations!!!
HispaniaSS13/ParadiseHispania pull request #71
Opened 2023-01-21 01:53 UTC by Tilk1

**El modo de juego  nations regresa**

![image](https://user-images.githubusercontent.com/24284918/213835664-a93024a5-f0d4-4106-9e64-f492f524295e.png)

![image](https://user-images.githubusercontent.com/24284918/213835659-b13b5da8-2e73-4157-81ae-db8479bb597e.png)

- No esta en la rotacion, solo es admin event
- Cada departamento se elige un lider y se notifica al usuario
- Cada miembro de la tripulacion ve los iconos de los demas departamentos
- Los asistentes son independientes
- La IA y los borgs tienen leyes especiales para mantener el orden
- Los borgs tienen un modulo llamado Nations (tanto los que ya estaban como los que llegan) poseen set de herramientas especial para mantener el orden mas avanzados
- Se regala una bandera a cada miembro del departamento que lo representa (excepto a los late joins)

2023-01-21 03:10 UTC, SagaStars commented
MIRENME, ESE SOY YO. EL QUE ESTA LLEVANDO EL CUERPO COMO HOS ESE SOY YO

2023-01-21 20:33 UTC, SagaStars requested changes
Me gusta mucho lo que veo, pero veo un problema grande. El texto dice que cortas conexion con Centcomm pero aun asi puedes llamar la shuttle para que los vengan a buscar >:(

Creo que seria buen momento para buscar una alternativa a como podria acabar el gamemode sin necesidad de llamar la shuttle de evacuacion. Alguna condicional para que un bando gane? Idk, me gustaria escuchar que piensas.

2023-01-21 20:33 UTC, SagaStars commented on data/mode.txt
> +extended
Bro?

2023-01-21 20:34 UTC, Tilk1 commented on data/mode.txt
> +extended
weird

2023-01-21 20:37 UTC, Tilk1 commented
> Me gusta mucho lo que veo, pero veo un problema grande. El texto dice que cortas conexion con Centcomm pero aun asi puedes llamar la shuttle para que los vengan a buscar >:(
> 
> Creo que seria buen momento para buscar una alternativa a como podria acabar el gamemode sin necesidad de llamar la shuttle de evacuacion. Alguna condicional para que un bando gane? Idk, me gustaria escuchar que piensas.

Si creo que se podrian cambiar los textos que se anuncian.  Este es un evento que requiere la presencia de un admin como minimo  y el deberia poder  decidir cuando es momento de llamar la shuttle.   Idealmente esto sucede cuando todas las naciones (que estan vivas)  llegan a un acuerdo de evacuar.   De lo contrario no se puede llamar la shuttle.

2023-01-21 20:42 UTC, SagaStars commented
> > Me gusta mucho lo que veo, pero veo un problema grande. El texto dice que cortas conexion con Centcomm pero aun asi puedes llamar la shuttle para que los vengan a buscar >:(
> > Creo que seria buen momento para buscar una alternativa a como podria acabar el gamemode sin necesidad de llamar la shuttle de evacuacion. Alguna condicional para que un bando gane? Idk, me gustaria escuchar que piensas.
> 
> Si creo que se podrian cambiar los textos que se anuncian. Este es un evento que requiere la presencia de un admin como minimo y el deberia poder decidir cuando es momento de llamar la shuttle. Idealmente esto sucede cuando todas las naciones (que estan vivas) llegan a un acuerdo de evacuar. De lo contrario no se puede llamar la shuttle.

Hm ya luego de pensarlo bien, lo mejor seria darle un panel a los admins para que puedan decidir cuando una nacion gano o quedan en paz, stalemate forzando un endround, pero, cambiar el texto tambien estaria bien y dejamos este cambio para otro PR.

2023-01-21 23:16 UTC, Tilk1 commented on data/mode.txt
> +extended
> Bro?

fixed

2023-01-22 01:21 UTC, Tilk1 commented
Se cambio el texto de anuncio por: 

" Nanotrasen ha decidido liquidar todos \
					los activos de la División de Centcom para pagar los honorarios legales masivos en los que se incurrirá. \
					Por lo tanto, todos los contratos de trabajo actuales son TERMINADOS INMEDIATAMENTE \
					. Cada departamento a partir de ahora es INDEPENDIENTE. \
					Tomaremos en cuenta el rescate con la shuttle solo si todos los departamentos \
					estan de acuerdo en llamarla. Que tengan una feliz  \
					estadia.", "FINAL DE TRANSMISSION, CENTCOM.

2023-01-23 01:32 UTC, SagaStars approved these changes
Funciona por ahora

2023-01-23 19:56 UTC, Helixis approved these changes

2023-01-23 19:56 UTC, merged