Nuevo evento, baños tapados!
HispaniaSS13/ParadiseHispania pull request #74
Opened 2023-01-23 00:25 UTC by Tilk1

Nuevo evento, baños tapados!

- Nuevo evento de tipo mundano
- Genera agua que tapa los inodoros y hace resbalar a la gente
- Nuevo item, sopapa destapador (plunger) para el janitor
- Se puede pedir el item en cargo  y el janitor comienza con uno en su locker
- El item tambien se puede usar como sombrero para parecer muy inteligente. Tecnicamente es un gorro

- Se agrego la variable pixelYoffset de dana de otro PR para mover los sombreros
- Corregi la chance del evento feed_me que era extremadamente baja ya que estaba

![image](https://user-images.githubusercontent.com/24284918/213948521-3d9c3fae-b38e-4d31-bceb-45598aed0115.png)

![image](https://user-images.githubusercontent.com/24284918/213948572-31373dbb-8157-4a6f-b27d-effb2a882fbd.png)

Sprite porteado baystation

2023-01-23 00:51 UTC, Tilk1 commented
https://media.discordapp.net/attachments/387645048386486273/1066882328950997022/Animation3.gif

https://cdn.discordapp.com/attachments/387645048386486273/1066882569490137158/Animation4.gif

2023-01-23 19:55 UTC, Helixis approved these changes

2023-01-23 19:56 UTC, Helixis approved these changes

2023-01-23 20:28 UTC, AsrielFBI reviewed
No me gusta nada que se modifique tanto el código base. Me huele a que generará demasiados problemas en el futuro. Sobretodo porque cada vez me da más la sensación de que a nadie le importa ese pequeño hecho.

2023-01-23 20:31 UTC, kokolo21 requested changes
Fijate las cosas que van en listas puedes agregarlas desde su propio archivo .dm haciendo "list1 =| list2" y listo. Diria que hagas eso para Event_container.dm.

2023-01-24 00:49 UTC, Tilk1 commented
Se tuvo en cuenta el comentario de ambos y ahora se movio el archivo event_containers a modular hispania para ahi ir agregando nuestros eventos. Todo lo modificado de ese archivo se quita y se pasa al nuevo

La unica modificacion al codigo base son 3 lineas

1- Para que los closets comiencen con 1 destapador
2- La crate de janitor de cargo que tenga 1 destapador
3- La variable de danaleja offset para los sprites que sera necesaria para este hat y para los otros futuros que traigamos. (actualmente  los testie y no funcionan como el elzra hat)   " standing.pixel_y = head.pixelYoffset  "

2023-01-24 05:00 UTC, Tilk1 commented
![image](https://user-images.githubusercontent.com/24284918/214213205-26b3a942-2c86-4e9c-afdc-f98af0a4bdef.png)

Se agrego modulo a los borgs janitor
Se agrego que el spawn del closet del janitor sea en modular_hispania
Se puede fabricar por autolathe en vez de pedir por cargo

Solo hay 1 linea que se agrega al codigo base , que es la de danaleja para los hats. El resto todo modular_hispania

2023-01-26 21:47 UTC, AsrielFBI approved these changes

2023-02-02 18:23 UTC, Helixis submitted a review, later dismissed

2023-02-02 22:52 UTC, Tilk1 commented
arreglados conflictos

2023-02-03 18:27 UTC, Tilk1 commented
El merge conflict mas tonto del universo

2023-02-03 19:39 UTC, kokolo21 approved these changes

2023-02-03 20:08 UTC, AsrielFBI approved these changes

2023-02-03 20:08 UTC, merged