DaBaby Remix
HispaniaSS13/ParadiseHispania pull request #84
Opened 2023-01-25 02:34 UTC by SagaStars

Mete un coñazo de cosas que mejoran la experiencia de dababy, ahora con mas equipamiento para la mayoria de departamentos, al igual que zonas extras para servicio.

Entre los cambios mas notables estan:
- El Ring de Bobby
- Sala de mantenimiento con un coñazo de maint spawners
- Baño
- Sala de Vendings de Arrivals
- Outlet diposal en Cargo
- Ligeros cambios esteticos en general
- Vault hecho un desastre
- Sala hardsuits para med
- Sala de chems y experimentor para ciencias
- Cocina y Bar EXTENDIDOS
- Un poco mas de espacio en sec
- Sala de canisters en inge

2023-01-25 03:16 UTC, Tilk1 commented
**YES DADABY !!!!**

Ahora bien: 

![image](https://user-images.githubusercontent.com/24284918/214471823-0b6777f9-482e-4447-9b22-0dd446cd42c4.png)

Esta seccion esta demasiado apretada. Los pasillos principales no deberian tener 1 solo tile. Como minimo 2.  Ya hay una maquina de cigarros y de comidas muy cerca. ¿Para que otras mas?. Los sillones tampoco les veo mucho sentido y la verdad quitar el terreno verde y la vegetacion no me agrada mucho. Preferia el pastito.

![image](https://user-images.githubusercontent.com/24284918/214472208-006a3c03-e9da-45d4-88ff-b0d9da7eceae.png)

El resto me parece bien obviamente necesita el arma principal de dadaby pero eso sera en otro PR. Las nuevas areas me parecen una buena adicion y el baño igual.  Se ha mantenido el espiritu de dadaby con excepcion de eso que remarque . Ademas de que queda muy asimetrico el pasillo de la izquierda de un tile con la derecha

2023-01-25 06:00 UTC, SagaStars commented
Gracias Nica por iluminarme los ojos, ya resolvi el problema con la asimetria de los pasillos, ahora sec esta mejor que nunca 
![image](https://user-images.githubusercontent.com/55407528/214491672-47a654be-0490-4dec-ab3b-a40064f969d8.png)

2023-01-25 22:21 UTC, Tilk1 requested changes
Mantengo mi opinion de los pasillos principales con 2 tiles

2023-01-26 21:43 UTC, AsrielFBI submitted a review, later dismissed

2023-01-27 10:26 UTC, AsrielFBI commented
> Mantengo mi opinion de los pasillos principales con 2 tiles

Solo te aviso por si no te has dado cuenta. Hacer un request changes sin ser maintainer no bloquea el merge, ni tampoco tiene validez frente a si un PR se acepta o no. (Literalmente ni siquiera se pone rojo el Request)

2023-01-27 17:17 UTC, Tilk1 commented
> > Mantengo mi opinion de los pasillos principales con 2 tiles
> 
> Solo te aviso por si no te has dado cuenta. Hacer un request changes sin ser maintainer no bloquea el merge, ni tampoco tiene validez frente a si un PR se acepta o no. (Literalmente ni siquiera se pone rojo el Request)
> 
> ![imagen](https://user-images.githubusercontent.com/56162938/215064913-fc2842f2-6bd2-4f43-95b4-56138690cca4.png)

No era mi idea bloquear el PR quedate tranquilo no le haria eso a  saga.  Efectivamente es la diferencia entre "Suggested changes"  y  "Requested changes"

2023-02-02 16:46 UTC, kokolo21 approved these changes

2023-02-02 22:49 UTC, Tilk1 approved these changes

2023-02-03 16:22 UTC, kokolo21 approved these changes

2023-02-03 16:24 UTC, AsrielFBI approved these changes

2023-02-03 16:24 UTC, merged